transletter/burse/urls.py
from django.urls import path

import burse.views

app_name = "burse"

urlpatterns = [
    path(
        "translators/",
        burse.views.TranslatorsView.as_view(),
        name="translators",
    ),
    path(
        "translator/<str:username>",
        burse.views.TranslatorView.as_view(),
        name="translator",
    ),
]

transletter/translation_request/urls.py
from django.urls import path

import translation_request.views

app_name = "translation_request"

urlpatterns = [
    path(
        "all/",
        translation_request.views.TranslationRequestListView.as_view(),
        name="translation_request_list",
    ),
    path(
        "<int:pk>/",
        translation_request.views.TranslationRequestView.as_view(),
        name="translation_request_detail",
    ),
    path(
        "create/<int:translator_id>",
        translation_request.views.CreateTranslationRequest.as_view(),
        name="create_translation_request",
    ),
    path(
        "<int:pk>/update/status/",
        translation_request.views.UpdateTranslationRequestStatusView.as_view(),
        name="update_translation_request_status",
    ),
]

transletter/translationrequest/urls.py
from django.urls import path

import translationrequest.views

app_name = "translation_request"

urlpatterns = [
    path(
        "request_translator/",
        translationrequest.views.RequestTranslatorView.as_view(),
        name="request_translator",
    ),
]

transletter/transletter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path

from landing import views

__all__ = ()

handler404 = views.Handler404View.as_view()
handler403 = views.Handler403View.as_view()
handler500 = views.Handler500View.as_view()

urlpatterns = [
    path("", include("landing.urls")),
    path("burse/", include("burse.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("translator_request/", include("translator_request.urls")),
    path("notifications/", include("notifications.urls")),
    path("projects/", include("projects.urls")),
    path("translation_request/", include("translation_request.urls")),
    path("rating/", include("rating.urls")),
    path("resume/", include("resume.urls")),
    path("auth/", include("accounts.urls")),
    path("auth/", include(django.contrib.auth.urls), name="auth_default"),
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.MEDIA_ROOT:
    urlpatterns += static(
        settings.MEDIA_URL + "avatars",
        document_root=settings.MEDIA_ROOT / "avatars",
    )
    urlpatterns += static(
        settings.MEDIA_URL + "cache",
        document_root=settings.MEDIA_ROOT / "cache",
    )

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

transletter/translation_request/forms.py
from django import forms

from projects.models import Project
from translation_request.models import (
    TranslationRequest,
    TranslationRequestMessage,
)
from transletter.mixins import BaseFormMixin
from transletter.utils import get_available_langs

__all__ = ()


class CreateTranslationRequestForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, user, *args, **kwargs):
        super(CreateTranslationRequestForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()
        self.fields["project"].queryset = Project.objects.filter(
            projectmembership__user=user,
            projectmembership__role="owner",
        )

    class Meta:
        model = TranslationRequest
        fields = (
            "project",
            "text",
            "price",
        )

    languages = forms.MultipleChoiceField(
        choices=get_available_langs(),
        required=True,
    )


class MessageForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = TranslationRequestMessage
        fields = ("content",)
        widgets = {
            "content": forms.TextInput(attrs={"placeholder": "Your message"}),
        }

transletter/translation_request/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db import models
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import pgettext_lazy
from django.views.generic import CreateView, DetailView, ListView, View

from accounts.models import User
from projects.models import Project, ProjectLanguage, ProjectMembership
from translation_request.forms import CreateTranslationRequestForm, MessageForm
from translation_request.models import (
    TranslationRequest,
    TranslationRequestMessage,
)

__all__ = ()


class TranslationRequestListView(LoginRequiredMixin, ListView):
    template_name = "translation_request/translation_request_list.html"
    paginate_by = 10

    def get_queryset(self):
        user = self.request.user
        return (
            TranslationRequest.objects.get_queryset()
            .filter(
                models.Q(author=user) | models.Q(translator=user),
            )
            .order_by("-created_at")
            .all()
        )


class TranslationRequestView(LoginRequiredMixin, DetailView):
    template_name = "translation_request/translation_request.html"
    model = TranslationRequest
    context_object_name = "translation_request"

    def get(self, request, pk, *args, **kwargs):
        translation_request = self.get_translation_request(pk)
        self.check_permissions(request.user, translation_request)
        form = MessageForm()
        return render(
            template_name=self.template_name,
            context={"translation_request": translation_request, "form": form},
            request=request,
        )

    def post(self, request, pk, *args, **kwargs):
        translation_request = self.get_translation_request(pk)
        self.check_permissions(request.user, translation_request)
        form = MessageForm(request.POST)
        if form.is_valid() and translation_request.status not in "RJCL":
            form.instance.author = request.user
            form.instance.translation_request = translation_request
            form.instance.save()
            form = MessageForm()
        return redirect(request.path)

    def get_translation_request(self, pk):
        translation_request = (
            TranslationRequest.objects.get_translation_request_detail(pk)
        )
        if translation_request is None:
            raise Http404()
        return translation_request

    def check_permissions(self, user, translation_request):
        if (
            user != translation_request.author
            and user != translation_request.translator
        ):
            raise PermissionDenied()


class CreateTranslationRequest(LoginRequiredMixin, CreateView):
    template_name = "translation_request/create_translation_request.html"
    form_class = CreateTranslationRequestForm
    success_url = reverse_lazy("translation_request:translation_request_list")

    def dispatch(self, request, translator_id, *args, **kwargs):
        translator = get_object_or_404(
            User.objects.filter(account__is_translator=True),
            pk=translator_id,
        )
        if translator == request.user:
            raise Http404()
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.translator = get_object_or_404(
            User.objects.filter(account__is_translator=True),
            pk=self.kwargs["translator_id"],
        )
        form.instance.author = self.request.user

        owned_projects = Project.objects.filter(
            projectmembership__user=self.request.user,
            projectmembership__role="owner",
        )
        if form.instance.project not in owned_projects:
            messages.error(
                self.request,
                pgettext_lazy(
                    "error message in views",
                    "You do not own the selected project.",
                ),
            )
            return self.render_form(form)

        translation_request_exist = TranslationRequest.objects.filter(
            author=self.request.user,
            status__in=["SE", "AC", "IP", "FN"],
            project=form.instance.project,
            translator=form.instance.translator,
        ).exists()
        if translation_request_exist:
            messages.error(
                self.request,
                pgettext_lazy(
                    "error message in views",
                    (
                        "You have already sent a similar "
                        "translation request to this translator"
                    ),
                ),
            )
            return self.render_form(form)

        project_membership_exist = ProjectMembership.objects.filter(
            user=form.instance.translator,
            project=form.instance.project,
        ).exists()
        if project_membership_exist:
            messages.error(
                self.request,
                pgettext_lazy(
                    "error message in views",
                    ("The translator is already in this project."),
                ),
            )
            return self.render_form(form)

        form.instance.languages = form.cleaned_data["languages"]
        translator_languages = set(form.instance.translator.account.languages)
        project_languages = set(
            ProjectLanguage.objects.filter(
                project__in=owned_projects,
            ).values_list("lang_code", flat=True),
        )
        selected_languages = set(form.instance.languages)
        if not selected_languages.issubset(
            translator_languages,
        ) or not selected_languages.issubset(project_languages):
            messages.error(
                self.request,
                pgettext_lazy(
                    "error message in views",
                    (
                        "The translator does not translate into these "
                        "languages, or they do not exist in your project"
                    ),
                ),
            )
            return self.render_form(form)

        form.instance.status = "SE"

        if form.instance.price > self.request.user.account.balance:
            messages.error(
                self.request,
                pgettext_lazy(
                    "error message in views",
                    "Insufficient funds on the account.",
                ),
            )
            return self.render_form(form)
        self.request.user.account.balance -= form.instance.price
        self.request.user.account.save()

        return super().form_valid(form)

    def render_form(self, form):
        return render(
            self.request,
            template_name=self.template_name,
            context={"form": form},
        )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class UpdateTranslationRequestStatusView(LoginRequiredMixin, View):
    def dispatch(self, request, pk, *args, **kwargs):
        translation_request = get_object_or_404(
            TranslationRequest,
            pk=pk,
        )
        if (
            translation_request.translator != request.user
            and translation_request.author != request.user
        ):
            raise PermissionDenied()
        return super().dispatch(
            request,
            pk,
            translation_request,
            *args,
            **kwargs,
        )

    def get(
        self,
        request,
        pk,
        translation_request,
        *args,
        **kwargs,
    ):
        to_status = request.GET.get("to_status", None)
        if to_status is not None:
            if request.user == translation_request.translator:
                if translation_request.status == "SE" and to_status == "AC":
                    translation_request.status = to_status
                    translation_request.save()
                    TranslationRequestMessage.objects.create(
                        translation_request=translation_request,
                        author=None,
                        content="The translator has accepted request",
                    )
                elif translation_request.status == "SE" and to_status == "RJ":
                    translation_request.status = to_status
                    translation_request.save()
                    translation_request.author.account.balance += (
                        translation_request.price
                    )
                    translation_request.author.account.save()
                    TranslationRequestMessage.objects.create(
                        translation_request=translation_request,
                        author=None,
                        content="The translator has rejected request",
                    )
                elif translation_request.status == "AC" and to_status == "IP":
                    exist = ProjectMembership.objects.filter(
                        user=translation_request.translator,
                        project=translation_request.project,
                    )
                    if not exist:
                        translation_request.status = to_status
                        translation_request.save()
                        ProjectMembership.objects.create(
                            user=translation_request.translator,
                            project=translation_request.project,
                            role="hired_translator",
                        )
                        url = request.build_absolute_uri(
                            reverse(
                                "projects:project_page",
                                kwargs={
                                    "slug": translation_request.project.slug,

transletter/translationrequest/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.translation import pgettext_lazy
from django.views.generic import View

from resume.models import ResumeFile
from translationrequest.forms import RequestTranslatorForm
from translationrequest.models import TranslatorRequest

__all__ = ()


class RequestTranslatorView(View):
    template_name = "translation_request/request_translator.html"
    success_url = reverse_lazy("dashboard:edit_account")

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, "translator_request"):
            raise Http404("TranslatorRequest already exists for this user")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        try:
            form = RequestTranslatorForm(
                instance={
                    "resume_form": request.user.account.resume,
                },
            )
        except Exception:
            form = RequestTranslatorForm()
        return render(
            request,
            template_name=self.template_name,
            context={"form": form},
        )

    def post(self, request):
        form = RequestTranslatorForm(request.POST, request.FILES)
        if form.is_valid():
            resume = form["resume_form"].save()
            files = request.FILES.getlist("files_form-file")
            for file in files:
                ResumeFile.objects.create(resume=resume, file=file)
            if request.user.account.resume:
                request.user.account.resume.delete()
            request.user.account.resume = resume
            request.user.account.save()
            TranslatorRequest.objects.create(
                user=request.user,
                resume=resume,
            )
            messages.success(
                request,
                pgettext_lazy(
                    "RequestTranslator create success",
                    "Your request to become a translator has been sent",
                ),
            )
            return redirect(reverse("dashboard:edit_account"))

        return render(
            request,
            template_name=self.template_name,
            context={"form": form},
        )

transletter/templates/translation_request/includes/translation_request_card.html
{% load i18n thumbnail %}
<a href="{% url 'translation_request:translation_request_detail' pk=translation_request.pk %}">
    <div class="ratings_section">
        <div class="d-flex justify-content-center mt-10">
            <div class="row w-100">
                <div class="col-md-12">
                    <div class="card">
                        <div class="comment-widgets m-b-20">
                            <div class="d-flex flex-row comment-row">
                                <div class="p-2">
                                    <span class="round">
                                        {% thumbnail translation_request.author.account.avatar "50x50" as avatar %}
                                            <img src="{{ avatar.url }}" alt="User Avatar" width="50px">
                                        {% empty %}
                                            <svg height="50px"
                                                 width="50px"
                                                 class="round"
                                                 xmlns="http://www.w3.org/2000/svg"
                                                 role="img"
                                                 aria-label="Placeholder: Avatar"
                                                 preserveAspectRatio="xMidYMid slice"
                                                 focusable="false">
                                                <title>{% translate "No image" %}</title>
                                                <rect width="100%" height="100%" fill="#55595c"></rect>
                                            </svg>
                                        {% endthumbnail %}
                                    </span>
                                </div>
                                <div class="comment-text w-100">
                                    <div class="row">
                                        <div class="col d-flex align-items-center">
                                            <h5>{% translate "Translation Request from" %} {{ translation_request.author.username }}</h5>
                                            {% if translation_request.status == "SE" %}
                                                <span class="badge rounded-pill text-bg-info ms-2 mb-2">Sent</span>
                                            {% elif translation_request.status == "RJ" %}
                                                <span class="badge rounded-pill text-bg-danger ms-2 mb-2">Rejected</span>
                                            {% elif translation_request.status == "AC" %}
                                                <span class="badge rounded-pill text-bg-success ms-2 mb-2">Accepted</span>
                                            {% elif translation_request.status == "IP" %}
                                                <span class="badge rounded-pill text-bg-info ms-2 mb-2">In progress</span>
                                            {% elif translation_request.status == "FN" %}
                                                <span class="badge rounded-pill text-bg-success ms-2 mb-2">Finished</span>
                                            {% elif translation_request.status == "CL" %}
                                                <span class="badge rounded-pill text-bg-secondary ms-2 mb-2">Closed</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="comment-footer col">
                                            <span class="date text-muted">{{ translation_request.created_at }} (UTC)</span>
                                            <span class="action-icons"></span>
                                        </div>
                                    </div>
                                    <p class="m-b-5 mt-10 text-muted">{{ translation_request.text|truncatechars_html:80|striptags|safe }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</a>