transletter/accounts/urls.py
from django.contrib.auth import views
from django.urls import path

import accounts.forms
import accounts.views

app_name = "accounts"

urlpatterns = [
    path("signup/", accounts.views.UserSignupView.as_view(), name="signup"),
    path(
        "login/",
        views.LoginView.as_view(
            template_name="accounts/login.html",
            form_class=accounts.forms.MyLoginForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(template_name="accounts/logout.html"),
        name="logout",
    ),
    path(
        "password_change/",
        views.PasswordChangeView.as_view(
            template_name="accounts/password_change.html",
            form_class=accounts.forms.MyPasswordChangeForm,
        ),
        name="password_change",
    ),
    path(
        "password_change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        views.PasswordResetView.as_view(
            template_name="accounts/password_reset.html",
            form_class=accounts.forms.MyPasswordResetForm,
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            form_class=accounts.forms.MyPasswordConfirmForm,
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "activate/<str:token>/",
        accounts.views.ActivateAccountView.as_view(),
        name="activate_account",
    ),
    path(
        "request_activation/",
        accounts.views.AccountActivationRequestView.as_view(),
        name="request_activation",
    ),
    path(
        "account/edit/",
        accounts.views.AccountEditView.as_view(),
        name="edit_account",
    ),
]

transletter/burse/urls.py
from django.urls import path

import burse.views

app_name = "burse"

urlpatterns = [
    path(
        "translators/",
        burse.views.TranslatorsView.as_view(),
        name="translators",
    ),
    path(
        "translator/<str:username>",
        burse.views.TranslatorView.as_view(),
        name="translator",
    ),
]

transletter/dashboard/urls.py
from django.urls import path

import dashboard.views

app_name = "dashboard"

urlpatterns = [
    path("", dashboard.views.IndexView.as_view(), name="index"),
]

transletter/landing/urls.py
from django.urls import path

from landing import views

app_name = "landing"

urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
]

transletter/projects/urls.py
from django.urls import path

import projects.views

app_name = "projects"

urlpatterns = [
    path(
        "",
        projects.views.ProjectsListView.as_view(),
        name="projects_list",
    ),
    path(
        "create/",
        projects.views.CreateProjectView.as_view(),
        name="create_project",
    ),
    path(
        "<slug:slug>/",
        projects.views.ProjectPageView.as_view(),
        name="project_page",
    ),
    path(
        "<slug:slug>/edit/",
        projects.views.ChangeProjectView.as_view(),
        name="edit_project",
    ),
    path(
        "<slug:slug>/members/",
        projects.views.ProjectMembersView.as_view(),
        name="project_members",
    ),
    path(
        "<slug:slug>/members/invite/",
        projects.views.AddProjectMemberView.as_view(),
        name="add_project_member",
    ),
    path(
        "invite/<str:token>/",
        projects.views.ActivateProjectMemberView.as_view(),
        name="activate_project_member",
    ),
    path(
        "<slug:slug>/members/<int:user_id>/delete/",
        projects.views.DeleteProjectMemberView.as_view(),
        name="delete_project_member",
    ),
    path(
        "<slug:slug>/members/<int:user_id>/update_role/",
        projects.views.UpdateProjectMemberView.as_view(),
        name="update_project_member",
    ),
    path(
        "<slug:slug>/languages/",
        projects.views.ProjectLanguagesView.as_view(),
        name="project_languages",
    ),
    path(
        "<slug:slug>/languages/add/",
        projects.views.AddProjectLangugeView.as_view(),
        name="add_project_language",
    ),
    path(
        "<slug:slug>/files/",
        projects.views.ProjectFilesView.as_view(),
        name="project_files",
    ),
    path(
        "<slug:slug>/files/upload/",
        projects.views.ProjectFilesUploadView.as_view(),
        name="project_files_upload",
    ),
    path(
        "<slug:slug>/files/<int:file_id>/update",
        projects.views.UpdateTranslationFileView.as_view(),
        name="update_translation_file",
    ),
    path(
        "<slug:slug>/files/<int:pk>/",
        projects.views.ProjectFileRowsView.as_view(),
        name="project_files_translate",
    ),
    path(
        "<slug:slug>/files/<int:file_pk>/<int:row_pk>/",
        projects.views.ProjectRowsTranslateView.as_view(),
        name="project_rows_translate",
    ),
    path(
        "<slug:slug>/files/<int:file_pk>/export/",
        projects.views.ProjectFileExportView.as_view(),
        name="project_file_export",
    ),
]

transletter/rating/urls.py
from django.urls import path

from rating.views import RatingCreateView

app_name = "rating"

urlpatterns = [
    path("<int:pk>/create/", RatingCreateView.as_view(), name="create_rating"),
]

transletter/transletter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path

from landing import views

__all__ = ()

handler404 = views.Handler404View.as_view()
handler403 = views.Handler403View.as_view()
handler500 = views.Handler500View.as_view()

urlpatterns = [
    path("", include("landing.urls")),
    path("burse/", include("burse.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("translator_request/", include("translator_request.urls")),
    path("notifications/", include("notifications.urls")),
    path("projects/", include("projects.urls")),
    path("translation_request/", include("translation_request.urls")),
    path("rating/", include("rating.urls")),
    path("resume/", include("resume.urls")),
    path("auth/", include("accounts.urls")),
    path("auth/", include(django.contrib.auth.urls), name="auth_default"),
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.MEDIA_ROOT:
    urlpatterns += static(
        settings.MEDIA_URL + "avatars",
        document_root=settings.MEDIA_ROOT / "avatars",
    )
    urlpatterns += static(
        settings.MEDIA_URL + "cache",
        document_root=settings.MEDIA_ROOT / "cache",
    )

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

transletter/rating/models.py
from django.db import models
from django.utils.translation import (
    gettext_lazy as _,
    pgettext_lazy,
)

from translation_request.models import TranslationRequest

__all__ = ()


RATING_CHOISES = (
    (1, pgettext_lazy("rating rank", "Very poor")),
    (2, pgettext_lazy("rating rank", "Poor")),
    (3, pgettext_lazy("rating rank", "Normal")),
    (4, pgettext_lazy("rating rank", "Good")),
    (5, pgettext_lazy("rating rank", "Very good")),
)


class RatingManager(models.Manager):
    def by_translator(self, username):
        return (
            self.get_queryset()
            .select_related(
                "translation_request",
            )
            .select_related("translation_request__author")
            .select_related("translation_request__translator")
            .filter(
                translation_request__translator__username=username,
            )
            .order_by("-created_at")
        )

    def by_translation_request(self, translation_request_id):
        return self.get_queryset().filter(
            translation_request__id=translation_request_id,
        )


class Rating(models.Model):
    objects = RatingManager()

    translation_request = models.OneToOneField(
        TranslationRequest,
        on_delete=models.CASCADE,
        related_name="rating",
    )
    text = models.TextField(
        pgettext_lazy("text field name", "text"),
    )
    rating = models.PositiveSmallIntegerField(
        pgettext_lazy(
            "rating field name",
            "rating",
        ),
        choices=RATING_CHOISES,
    )
    created_at = models.DateTimeField(
        pgettext_lazy("created_at field name", "created at"),
        auto_now_add=True,
        null=True,
    )

    def __str__(self):
        verbose = _(
            (
                "Translation request №"
                f"{self.translation_request.id}"
                " rating by "
                f"{self.translation_request.author}"
            ),
        )
        return str(verbose)

    class Meta:
        verbose_name = pgettext_lazy(
            "verbose name for rating",
            "rating",
        )
        verbose_name_plural = pgettext_lazy(
            "verbose name plural for rating",
            "ratings",
        )

transletter/rating/forms.py
from django import forms

from rating.models import Rating
from transletter.mixins import BaseFormMixin

__all__ = ()


class RatingAdminForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = (
            model.translation_request.field.name,
            model.text.field.name,
            model.rating.field.name,
        )


class RatingForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(RatingForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = Rating
        fields = ["text", "rating"]

transletter/rating/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils.translation import pgettext_lazy
from django.views.generic import CreateView

from rating.forms import RatingForm
from rating.models import Rating
from translation_request.models import (
    TranslationRequest,
    TranslationRequestMessage,
)

__all__ = ()


class RatingCreateView(LoginRequiredMixin, CreateView):
    template_name = "rating/create_rating.html"
    form_class = RatingForm
    success_url = reverse_lazy("translation_request:translation_request_list")

    def dispatch(self, request, *args, **kwargs):
        translation_request = get_object_or_404(
            TranslationRequest.objects.select_related("translator"),
            pk=self.kwargs.get("pk"),
        )
        if translation_request.status != "CL":
            raise Http404()
        rating = Rating.objects.filter(translation_request=translation_request)
        if rating:
            raise Http404()
        if request.user != translation_request.author:
            raise PermissionDenied()
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        translation_request = get_object_or_404(
            TranslationRequest.objects.select_related("translator"),
            pk=self.kwargs.get("pk"),
        )
        rating = Rating.objects.filter(translation_request=translation_request)
        if rating:
            messages.error(
                self.request,
                pgettext_lazy(
                    "error message rating is created",
                    "Rating already exists",
                ),
            )
            return self.render_form(form)
        form.instance.translation_request = translation_request
        TranslationRequestMessage.objects.create(
            translation_request=translation_request,
            author=None,
            content=("The author of the request rated the translator."),
        )
        messages.success(
            self.request,
            pgettext_lazy(
                "success message in rating create view",
                "Rating successfully created",
            ),
        )
        return super().form_valid(form)

    def render_form(self, form):
        return render(
            self.request,
            template_name=self.template_name,
            context={"form": form},
        )

transletter/templates/includes/footer.html
{% load static i18n %}
<footer class="site-footer">
    <div class="container">
        <div class="site-footer-inner">
            <div class="brand footer-brand">
                <a href="{% url 'landing:index' %}">
                    <img width="32px"
                         height="32px"
                         class="header-logo-image"
                         src="{% static 'img/transletter.png' %}"
                         alt="Logo">
                </a>
            </div>
            <ul class="footer-links list-reset">
                <li>
                    <a href="mailto:trans.letter@ya.ru">trans.letter@ya.ru</a>
                </li>
            </ul>
            <ul class="footer-social-links list-reset">
            </ul>
            <div class="footer-copyright">
                &copy;&nbsp;2023-<span id="footerYear">{% now "Y" %}</span>&nbsp;TransLetter, {% translate "all rights reserved" %}
            </div>
        </div>
    </div>
</footer>

transletter/templates/includes/form.html
{% for field in form %}
    <div class="form-group mb-3">
        <label for="{{ field.auto_id }}" class="form-label">{{ field.label }}</label>
        {{ field }}
        {% if field.errors %}
            {% for error in field.errors %}<div class="invalid-feedback">{{ error|safe }}</div>{% endfor %}
        {% endif %}
        {% if field.help_text %}
            <div class="form-text text-muted">
                <p>{{ field.help_text|safe }}</p>
            </div>
        {% endif %}
    </div>
{% endfor %}
{% if form.non_field_errors %}
    <div class="alert alert-danger">
        {% for error in form.non_field_errors %}{{ error|safe }}{% endfor %}
    </div>
{% endif %}

transletter/templates/includes/header-dashboard.html
{% load static thumbnail i18n %}
<header class="header" id="header">
    <div class="header_toggle">
        <i class='bx bx-menu' id="header-toggle"></i>
    </div>
    <div class="header_right">
        <a href="{% url 'notifications:all' %}">
            <div class="header_notification{% if request.resolver_match.view_name == 'notifications:all' %} selected{% endif %}">
                <i class='bx bxs-bell'></i>
            </div>
        </a>
        <div class="header_img">
            {% thumbnail request.user.account.avatar "300x300" as avatar %}
                <img src="{{ avatar.url }}" alt="Avatar">
            {% empty %}
                <svg alt="Avatar"
                     xmlns="http://www.w3.org/2000/svg"
                     role="img"
                     aria-label="Placeholder: Thumbnail"
                     preserveAspectRatio="xMidYMid slice"
                     focusable="false">
                    <title>{% translate "No image" %}</title>
                    <rect width="100%" height="100%" fill="#55595c"></rect>
                </svg>
            {% endthumbnail %}
        </div>
    </div>
</header>
<div class="l-navbar" id="nav-bar">
    {% with request.resolver_match.view_name as view_name %}
        <nav class="nav">
            <div>
                <form method="post" id="logoutForm" action="{% url 'accounts:logout' %}">
                    {% csrf_token %}
                </form>
                <a href="{% url 'dashboard:index' %}" class="nav_logo">
                    <img src="{% static 'img/transletter.png' %}"
                         alt="Logo"
                         width="25"
                         height="25">
                    <span class="nav_logo-name">TransLetter</span>
                </a>
                <div class="nav_list">
                    <a href="{% url 'dashboard:index' %}"
                       class="nav_link{% if view_name == 'dashboard:index' %} active{% endif %}">
                        <i class='bx bx-home nav_icon'></i>
                        <span class="nav_name">{% translate "Home" %}</span>
                    </a>
                    <a href="{% url 'projects:projects_list' %}"
                       class="nav_link{% if view_name == 'projects:projects_list' %} active{% endif %}">
                        <i class='bx bx-grid-alt nav_icon'></i>
                        <span class="nav_name">{% translate "Projects" %}</span>
                    </a>
                    <a href="{% url 'translation_request:translation_request_list' %}"
                       class="nav_link{% if view_name == 'translation_request:translation_request_list' %} active{% endif %}">
                        <i class='bx bx-git-pull-request'></i>
                        <span class="nav_name">{% translate "Translation requests" %}</span>
                    </a>
                    <a href="{% url 'burse:translators' %}"
                       class="nav_link{% if view_name == 'burse:translators' %} active{% endif %}">
                        <i class='bx bxs-credit-card nav_icon'></i>
                        <span class="nav_name">{% translate "Burse" %}</span>
                    </a>
                    {% if perms.translator_request.edit_translator_request %}
                        <a href="{% url 'translator_request:translator_requests' %}"
                           class="nav_link{% if view_name == 'translator_request:translator_requests' %} active{% endif %}">
                            <i class='bx bxs-chat nav_icon'></i>
                            <span class="nav_name">{% translate "Translator requests" %}</span>
                        </a>
                    {% endif %}
                    <a href="{% url 'translator_request:request_translator' %}"
                       class="nav_link{% if view_name == 'translator_request:request_translator' %} active{% endif %}">
                        <i class='bx bx-plus nav_icon'></i>
                        <span class="nav_name">{% translate "Request translator" %}</span>
                    </a>
                </div>
            </div>
            <div>
                <a href="{% url 'accounts:edit_account' %}"
                   class="nav_link{% if view_name == 'accounts:edit_account' %} active{% endif %}">
                    <i class='bx bxs-user nav_icon'></i>
                    <span class="nav_name">{% translate "Account" %}</span>
                </a>
                <a href="{% url 'accounts:password_change' %}"
                   class="nav_link{% if view_name == 'accounts:password_change' %} active{% endif %}">
                    <i class='bx bxs-lock-alt nav_icon'></i>
                    <span class="nav_name">{% translate "Change password" %}</span>
                </a>
                <a onclick="document.getElementById('logoutForm').submit();"
                   href="#"
                   class="nav_link">
                    <i class='bx bx-log-out nav_icon'></i>
                    <span class="nav_name">{% translate "Logout" %}</span>
                </a>
            </div>
        </nav>
    {% endwith %}
</div>

transletter/templates/includes/header.html
{% load static i18n %}
<header>
    <nav class="navbar navbar-expand-xl bg-body-tertiary rounded d-flex flex-wrap saas_navbar"
         aria-label="TransLetternavbar">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'landing:index' %}">
                <img src="{% static 'img/transletter.png' %}"
                     alt="Logo"
                     width="30"
                     height="30"
                     class="d-inline-block align-text-top">
                TransLetter
            </a>
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#TransLetter"
                    aria-controls="TransLetter"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% with request.resolver_match.view_name as view_name %}
                <div class="collapse navbar-collapse justify-content-end flex-nowrap"
                     id="TransLetter">
                    <ul class="nav nav-pills nav-fill mt-xs-2 mt-md-2 mt-lg-2 mt-xl-0 mt-2">
                        <li class="nav-item">
                            <a href="{% url 'landing:about' %}"
                               class="nav-link{% if view_name == 'landing:about' %} active{% endif %}">{% translate "About" %}</a>
                        </li>
                        {% if request.user.is_anonymous %}
                            <li class="nav-item">
                                <a href="{% url 'accounts:login' %}"
                                   class="nav-link{% if view_name == 'accounts:login' %} active{% endif %}">{% translate "Login" %}</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'accounts:signup' %}"
                                   class="nav-link{% if view_name == 'accounts:signup' %} active{% endif %}">{% translate "Signup" %}</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="{% url 'dashboard:index' %}"
                                   class="nav-link{% if view_name == 'dashboard:index' %} active{% endif %}">{% translate "Dashboard" %}</a>
                            </li>
                            <li class="nav-item">
                                <form method="post" id="logoutForm" action="{% url 'accounts:logout' %}">
                                    {% csrf_token %}
                                </form>
                                <a onclick="document.getElementById('logoutForm').submit();"
                                   href="#"
                                   class="nav-link">{% translate "Logout" %}</a>
                            </li>
                        {% endif %}
                        {% if request.user.is_staff %}
                            <li class="nav-item">
                                <a href="{% url 'admin:index' %}" class="nav-link">{% translate "Admin" %}</a>
                            </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <select onchange="this.form.submit()"
                                class="form-select ms-lg-2 mt-xs-2 mt-md-2 mt-lg-2 mt-xl-0 mt-2"
                                name="language">
                            {% get_current_language as LANGUAGE_CODE %}
                            {% get_available_languages as LANGUAGES %}
                            {% get_language_info_list for LANGUAGES as languages %}
                            {% for language in languages %}
                                <option value="{{ language.code }}"
                                        {% if language.code == LANGUAGE_CODE %}selected{% endif %}>
                                    {{ language.name_local }}
                                </option>
                            {% endfor %}
                            <option value="{{ language.code }}" disabled>{% translate "Russian" %} (Soon)</option>
                        </select>
                    </form>
                </div>
            {% endwith %}
        </div>
    </nav>
</header>

transletter/templates/includes/pagination.html
{% load static %}
<nav class="mt-3">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ page_obj.previous_page_number }}"
                   aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;&laquo;</span>
            </li>
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;</span>
            </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <li class="page-item active">
                    <span class="page-link">{{ num }}</span>
                </li>
            {% elif num > page_obj.number|add:"-2" and num < page_obj.number|add:"2" %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% elif num == page_obj.number|add:"-2" or num == page_obj.number|add:"2" %}
                <li class="page-item disabled">
                    <span class="page-link">...</span>
                </li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ page_obj.next_page_number }}"
                   aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item">
                <a class="page-link"
                   href="?page={{ page_obj.paginator.num_pages }}"
                   aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&raquo;</span>
            </li>
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&raquo;&raquo;</span>
            </li>
        {% endif %}
    </ul>
</nav>
<script src="{% static 'js/adaptPagination.js' %}"></script>

transletter/templates/includes/rating.html
{% load thumbnail i18n %}
<div class="ratings_section">
    <div class="row mt-10">
        <div class="col">
            <div class="card">
                <div class="comment-widgets mb-20">
                    <div class="d-flex flex-row comment-row">
                        <div class="comment-text w-100">
                            <div class="row">
                                <h5 class="col">{{ rating.translation_request.author.username }}</h5>
                            </div>
                            <div class="row">
                                <div class="comment-footer col">
                                    <span class="date text-muted">{{ rating.created_at }} (UTC)</span>
                                </div>
                            </div>
                            <p class="mt-3 mb-0 text-muted">{% translate "Rating" %}: {{ rating.get_rating_display }}</p>
                            <p class="mt-1 text-muted">{{ rating.text|safe }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

transletter/templates/includes/toasts.html
{% load static %}
{% if messages %}
    <div class="toast-container toast-custom"
         aria-live="polite"
         aria-atomic="true">
        {% for message in messages %}
            <div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                <div class="toast-header">
                    <img src="{% static 'img/transletter.png' %}"
                         class="bd-placeholder-img rounded me-2"
                         width="20"
                         height="20">
                    <strong class="me-auto">TransLetter</strong>
                    <button type="button"
                            class="btn-close"
                            data-bs-dismiss="toast"
                            aria-label="Close"></button>
                </div>
                <div class="toast-body">{{ message }}</div>
            </div>
        {% endfor %}
    </div>
{% endif %}