transletter/burse/urls.py
from django.urls import path

import burse.views

app_name = "burse"

urlpatterns = [
    path(
        "translators/",
        burse.views.TranslatorsView.as_view(),
        name="translators",
    ),
    path(
        "translator/<str:username>",
        burse.views.TranslatorView.as_view(),
        name="translator",
    ),
]

transletter/projects/urls.py
from django.urls import path

import projects.views

app_name = "projects"

urlpatterns = [
    path(
        "",
        projects.views.ProjectsListView.as_view(),
        name="projects_list",
    ),
    path(
        "create/",
        projects.views.CreateProjectView.as_view(),
        name="create_project",
    ),
    path(
        "<slug:slug>/",
        projects.views.ProjectPageView.as_view(),
        name="project_page",
    ),
    path(
        "<slug:slug>/edit/",
        projects.views.ChangeProjectView.as_view(),
        name="edit_project",
    ),
    path(
        "<slug:slug>/members/",
        projects.views.ProjectMembersView.as_view(),
        name="project_members",
    ),
    path(
        "<slug:slug>/members/invite/",
        projects.views.AddProjectMemberView.as_view(),
        name="add_project_member",
    ),
    path(
        "invite/<str:token>/",
        projects.views.ActivateProjectMemberView.as_view(),
        name="activate_project_member",
    ),
    path(
        "<slug:slug>/members/<int:user_id>/delete/",
        projects.views.DeleteProjectMemberView.as_view(),
        name="delete_project_member",
    ),
    path(
        "<slug:slug>/members/<int:user_id>/update_role/",
        projects.views.UpdateProjectMemberView.as_view(),
        name="update_project_member",
    ),
    path(
        "<slug:slug>/languages/",
        projects.views.ProjectLanguagesView.as_view(),
        name="project_languages",
    ),
    path(
        "<slug:slug>/languages/add/",
        projects.views.AddProjectLangugeView.as_view(),
        name="add_project_language",
    ),
    path(
        "<slug:slug>/files/",
        projects.views.ProjectFilesView.as_view(),
        name="project_files",
    ),
    path(
        "<slug:slug>/files/upload/",
        projects.views.ProjectFilesUploadView.as_view(),
        name="project_files_upload",
    ),
    path(
        "<slug:slug>/files/<int:file_id>/update",
        projects.views.UpdateTranslationFileView.as_view(),
        name="update_translation_file",
    ),
    path(
        "<slug:slug>/files/<int:pk>/",
        projects.views.ProjectFileRowsView.as_view(),
        name="project_files_translate",
    ),
    path(
        "<slug:slug>/files/<int:file_pk>/<int:row_pk>/",
        projects.views.ProjectRowsTranslateView.as_view(),
        name="project_rows_translate",
    ),
    path(
        "<slug:slug>/files/<int:file_pk>/export/",
        projects.views.ProjectFileExportView.as_view(),
        name="project_file_export",
    ),
]

transletter/transletter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
import django.contrib.auth.urls
from django.urls import include, path

from landing import views

__all__ = ()

handler404 = views.Handler404View.as_view()
handler403 = views.Handler403View.as_view()
handler500 = views.Handler500View.as_view()

urlpatterns = [
    path("", include("landing.urls")),
    path("burse/", include("burse.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("translator_request/", include("translator_request.urls")),
    path("notifications/", include("notifications.urls")),
    path("projects/", include("projects.urls")),
    path("translation_request/", include("translation_request.urls")),
    path("rating/", include("rating.urls")),
    path("resume/", include("resume.urls")),
    path("auth/", include("accounts.urls")),
    path("auth/", include(django.contrib.auth.urls), name="auth_default"),
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
]

if settings.MEDIA_ROOT:
    urlpatterns += static(
        settings.MEDIA_URL + "avatars",
        document_root=settings.MEDIA_ROOT / "avatars",
    )
    urlpatterns += static(
        settings.MEDIA_URL + "cache",
        document_root=settings.MEDIA_ROOT / "cache",
    )

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

transletter/projects/models.py
from pathlib import Path
import uuid

from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.translation import pgettext_lazy

from accounts.models import User
from transletter.utils import get_available_langs
from transletter.validators import validate_translation_file

__all__ = ()


class Project(models.Model):
    def get_path_for_file(self, filename):
        return f"projects/{self.pk}/avatar/{filename}"

    avatar = models.ImageField(
        pgettext_lazy("avatar field name", "avatar"),
        upload_to=get_path_for_file,
        null=True,
        blank=True,
    )
    name = models.CharField(
        pgettext_lazy("name field name", "name"),
        max_length=255,
    )
    description = models.TextField(
        pgettext_lazy("description field name", "description"),
        null=True,
        blank=True,
    )
    slug = models.SlugField(
        pgettext_lazy("slug field name", "slug"),
        max_length=200,
        unique=True,
        help_text="a-z, 0-9, _, -",
    )
    created_at = models.DateTimeField(
        pgettext_lazy("created at field name", "created at"),
        auto_now_add=True,
        null=True,
    )
    last_activity = models.DateTimeField(
        pgettext_lazy("last activity field name", "last activity"),
        auto_now_add=True,
        null=True,
    )
    public = models.BooleanField(
        pgettext_lazy("public field name", "public"),
        default=False,
    )
    source_lang = models.CharField(
        pgettext_lazy("source language field name", "source language"),
        max_length=10,
        choices=get_available_langs(),
    )
    members = models.ManyToManyField(
        User,
        through="ProjectMembership",
        related_name="projects",
    )

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = pgettext_lazy("verbose name for project", "project")
        verbose_name_plural = pgettext_lazy(
            "verbose name plural for projects",
            "projects",
        )


class ProjectMembership(models.Model):
    ROLES = (
        ("owner", pgettext_lazy("role name", "Owner")),
        ("admin", pgettext_lazy("role name", "Administrator")),
        ("static_translator", pgettext_lazy("role name", "Static translator")),
        ("hired_translator", pgettext_lazy("role name", "Hired translator")),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=ROLES)

    def __str__(self) -> str:
        return f"{self.project} -> {self.user.username}"


class ProjectLanguage(models.Model):
    LANGUAGES = get_available_langs()

    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="languages",
    )
    lang_code = models.CharField(
        pgettext_lazy("project languge lang code field name", "language"),
        max_length=10,
        choices=LANGUAGES,
    )

    def __str__(self) -> str:
        language_dict = dict(self.LANGUAGES)
        return language_dict.get(self.lang_code, "")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["project", "lang_code"],
                name="unique_lang",
            ),
        ]


class TranslationFile(models.Model):
    def get_path_for_file(self, filename):
        return (
            f"projects/{self.project_language.project_id}"
            f"/{self.project_language.lang_code}/"
            f"{str(uuid.uuid4())}/{filename}"
        )

    project_language = models.ForeignKey(
        ProjectLanguage,
        on_delete=models.CASCADE,
        related_name="files",
    )
    metadata = models.JSONField(null=True, blank=True)
    file = models.FileField(
        upload_to=get_path_for_file,
        validators=[
            FileExtensionValidator(
                allowed_extensions=settings.TRANSLATION_FILE_FORMATS,
            ),
            validate_translation_file,
        ],
    )

    def filename(self):
        return Path(self.file.name).name

    def __str__(self) -> str:
        return self.filename()


class TranslationRow(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    msg_context = models.TextField(null=True, blank=True)
    msg_id = models.TextField()
    msg_str = models.TextField()
    occurrences = models.JSONField(default=list, null=True, blank=True)
    translation_file = models.ForeignKey(
        TranslationFile,
        on_delete=models.CASCADE,
        related_name="rows",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=[
                    "msg_id",
                    "msg_context",
                    "translation_file",
                ],
                name="unique_row",
            ),
        ]


class TranslationComment(models.Model):
    translation_row = models.ForeignKey(
        TranslationRow,
        on_delete=models.CASCADE,
        related_name="comments",
    )
    comment = models.TextField(
        pgettext_lazy("comment field name", "comment"),
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="translation_comments",
    )
    created_at = models.DateTimeField(auto_now_add=True, null=True)

transletter/projects/forms.py
from django import forms
from django.utils.translation import pgettext_lazy

from projects import models
from transletter.mixins import BaseFormMixin


__all__ = ()


class CreateProjectForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(CreateProjectForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = models.Project
        fields = (
            models.Project.name.field.name,
            models.Project.description.field.name,
            models.Project.slug.field.name,
            models.Project.source_lang.field.name,
        )


class AddProjectMemberForm(forms.Form, BaseFormMixin):
    email = forms.EmailField(
        label=pgettext_lazy("add member form", "Email"),
        help_text=pgettext_lazy(
            "add member form",
            "Enter the user's email address",
        ),
    )
    email_header = forms.CharField(
        label=pgettext_lazy("add member form", "Email header"),
        help_text=pgettext_lazy(
            "add member form",
            "Enter the title of the email",
        ),
        max_length=50,
    )
    email_text = forms.CharField(
        help_text=pgettext_lazy(
            "add member form",
            "Enter the text of the email",
        ),
        widget=forms.Textarea(),
    )

    def __init__(self, *args, **kwargs):
        super(AddProjectMemberForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = models.Project
        fields = (
            "email_address",
            "email_header",
            "email_text",
        )


CHOICES = [
    (key, value)
    for key, value in models.ProjectMembership.ROLES
    if key not in ["owner", "hired_translator"]
]
blank_choice = [("", pgettext_lazy("add member form", "--- Choose role ---"))]


class UpdateProjectMemberForm(forms.Form, BaseFormMixin):
    role = forms.TypedChoiceField(choices=blank_choice + CHOICES)

    def __init__(self, *args, **kwargs):
        super(UpdateProjectMemberForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = models.ProjectMembership
        fields = ("role",)


class ProjectChangeForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(ProjectChangeForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = models.Project
        fields = (
            "name",
            "slug",
            "description",
        )


class ProjectAvatarChangeForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(ProjectAvatarChangeForm, self).__init__(*args, **kwargs)
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "file-upload"

    class Meta:
        model = models.Project
        fields = ("avatar",)


class TranslationFileForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(TranslationFileForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = models.TranslationFile
        fields = ("file", "project_language")
        widgets = {
            "project_language": forms.Select(attrs={"class": "form-control"}),
        }


class UpdateTranslationFileForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(UpdateTranslationFileForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = models.TranslationFile
        fields = ("file",)


class TranslationRowEditForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(TranslationRowEditForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = models.TranslationRow
        fields = ("msg_str",)
        labels = {
            "msg_str": pgettext_lazy("translation edit label", "Translation"),
        }


class AddLanguageForm(forms.ModelForm, BaseFormMixin):
    def __init__(self, *args, **kwargs):
        super(AddLanguageForm, self).__init__(*args, **kwargs)
        self.set_field_attributes()

    class Meta:
        model = models.ProjectLanguage
        fields = ("lang_code",)

transletter/templates/projects/includes/file_card.html
{% load i18n thumbnail %}
<div class="col">
    <div class="card h-100 shadow-sm item_card is-revealing zoomable-card">
        <a href="{% url 'projects:update_translation_file' slug=slug file_id=file.pk %}">
            <div class="badge bg-info text-black position-absolute download_image">
                <i class="fa-solid fa-pen"></i>
            </div>
        </a>
        <div class="card-body">
            <h2>File №{{ forloop.counter }}</h2>
            {{ file.filename }}
        </div>
        <a class="btn btn-primary text-end float-end"
           href="{% url 'projects:project_files_translate' slug=slug pk=file.id %}"><i class="fa-solid fa-plus"></i> {% translate "Translate" %}</a>
        <a class="btn btn-success text-end float-end"
           href="{% url 'projects:project_file_export' slug=slug file_pk=file.id %}"><i class="fa-solid fa-plus"></i> {% translate "Export" %}</a>
    </div>
</div>

transletter/templates/projects/includes/files_card.html
{% load i18n thumbnail %}
<div class="col">
    <div class="card h-100 shadow-sm item_card is-revealing zoomable-card">
        <div class="card-body">
            <h2>File №{{ forloop.counter }}</h2>
            {{ file.filename }}
        </div>
        <a class="btn btn-primary text-end float-end"
           href="{% url 'projects:project_files_translate' slug=slug pk=file.id %}"><i class="fa-solid fa-plus"></i> {% translate "Translate" %}</a>
        <a class="btn btn-success text-end float-end"
           href="{% url 'projects:project_file_export' slug=slug file_pk=file.id %}"><i class="fa-solid fa-plus"></i> {% translate "Export" %}</a>
    </div>
</div>

transletter/templates/projects/includes/language_card.html
{% load i18n thumbnail %}
<div class="col">
    <div class="card h-100 shadow-sm item_card is-revealing zoomable-card">
        <div class="card-body">
            <h5 class="card-title text-white">
                {{ language.get_lang_code_display }}
                {% if language.lang_code == language.project.source_lang %}
                    <span class="badge rounded-pill text-bg-primary">{% translate "Source language" %}</span>
                {% endif %}
            </h5>
            <p>{% translate "Files count" %}: {{ language.files.count }}</p>
        </div>
    </div>
</div>

transletter/templates/projects/includes/member_card.html
{% load static i18n thumbnail %}
<div class="col mb-5">
    <div class="card h-100 shadow-sm item_card is-revealing">
        {% thumbnail member.user.account.avatar "300x300" as avatar %}
            <img class="card-img-top card-img-bottom img-fluid" src="{{ avatar.url }}">
        {% empty %}
            <svg class="card-img-top card-img-bottom img-fluid"
                 width="100%"
                 height="300px"
                 xmlns="http://www.w3.org/2000/svg"
                 role="img"
                 aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice"
                 focusable="false">
                <title>{% translate "No image" %}</title>
                <rect width="100%" height="100%" fill="#55595c"></rect>
            </svg>
        {% endthumbnail %}
    </a>
    <div class="card-body">
        <h5 class="card-title text-white">
            {{ member.user.first_name|default:member.user.username }}
            {% if member.user.first_name != "" %}{{ member.user.last_name }}{% endif %}
        </h5>
        <p class="card-text text-muted">{{ member.account.about|truncatechars_html:80|striptags|safe }}</p>
        <p class="card-text text-muted">{% translate "Role" %}: {{ member.get_role_display }}</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                {% if active_user_role.role == "owner" or active_user_role.role == "admin" %}
                    {% if member.role != "owner" and member.role != "hired_translator" %}
                        {% if active_user_role.role == "admin" and member.role == "admin" %}
                        {% else %}
                            <a href="{% url 'projects:delete_project_member' slug=slug user_id=member.user_id %}"
                               class="btn btn-sm btn-outline-danger">{% translate "Delete" %}</a>
                        {% endif %}
                    {% endif %}
                    {% if member.role != "owner" and member.role != "hired_translator" and active_user_role.role != "admin" %}
                        <a href="{% url 'projects:update_project_member' slug=slug user_id=member.user_id %}"
                           class="btn btn-sm btn-outline-secondary">{% translate "Update role" %}</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </a>
</div>
</div>
</div>

transletter/templates/projects/includes/project_card.html
{% load i18n thumbnail %}
<div class="col">
    <div class="card h-100 shadow-sm item_card is-revealing zoomable-card">
        <a href="{% url 'projects:project_page' slug=project.slug %}">
            {% thumbnail project.avatar "300x300" as avatar %}
                <img class="card-img-top card-img-bottom img-fluid" src="{{ avatar.url }}">
            {% empty %}
                <svg class="card-img-top card-img-bottom img-fluid"
                     width="100%"
                     height="300px"
                     xmlns="http://www.w3.org/2000/svg"
                     role="img"
                     aria-label="Placeholder: Thumbnail"
                     preserveAspectRatio="xMidYMid slice"
                     focusable="false">
                    <title>{% translate "No image" %}</title>
                    <rect width="100%" height="100%" fill="#55595c"></rect>
                </svg>
            {% endthumbnail %}
        </a>
        <div class="card-body">
            <a href="{% url 'projects:project_page' slug=project.slug %}">
                <h5 class="card-title text-white">{{ project.name }}</h5>
                <p class="card-text">{{ project.desctiption|truncatechars_html:80|striptags|safe }}</p>
            </a>
        </div>
    </div>
</div>

transletter/templates/projects/includes/projects_nav.html
{% load i18n %}
{% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link{% if view_name == 'projects:project_page' %} active{% else %} text-muted{% endif %}"
               aria-current="page"
               href="{% url 'projects:project_page' slug=slug %}">{% translate "Info" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link{% if view_name == 'projects:project_members' %} active{% else %} text-muted{% endif %}"
               href="{% url 'projects:project_members' slug=slug %}">{% translate "Members" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link{% if view_name == 'projects:project_files' %} active{% else %} text-muted{% endif %}"
               href="{% url 'projects:project_files' slug=slug %}">{% translate "Files" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link{% if view_name == 'projects:project_languages' %} active{% else %} text-muted{% endif %}"
               href="{% url 'projects:project_languages' slug=slug %}">{% translate "Languages" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link{% if view_name == 'projects:edit_project' %} active{% else %} text-muted{% endif %}"
               href="{% url 'projects:edit_project' slug=slug %}">{% translate "Edit" %}</a>
        </li>
    </ul>
{% endwith %}

transletter/templates/projects/includes/row_card.html
{% load i18n thumbnail %}
<div class="col">
    <div class="card h-100 shadow-sm item_card is-revealing zoomable-card">
        <div class="card-body">
            <a href="{% url 'projects:project_rows_translate' slug=slug file_pk=row.translation_file_id row_pk=row.id %}">
                <h5 class="card-text text-white">{{ row.msg_id|truncatechars_html:45|striptags|safe }}</h5>
                {% if row.msg_str %}
                    <p class="card-text text-bg-primary">{{ row.msg_str|truncatechars_html:45|striptags|safe }}</p>
                {% else %}
                    <p class="text-bg-danger">{% translate "Not translated yet" %}</p>
                {% endif %}
            </a>
        </div>
    </div>
</div>